version: '3.3'
services:
  app:
    build: .
    restart: on-failure
    env_file: ./.env.docker
    volumes:
      - prodia:/code/media
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  celery:
    build: .
    restart: on-failure
    env_file: ./.env.docker
    command:
      # - ls
      - sh
      - ./start_celery.sh
    volumes:
      - prodia:/code/media
    depends_on:
      - app
      - db
      - redis
  db:
    image: postgres:alpine
    container_name: postgres_db
    restart: always
    volumes:
      - prodia_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: weatherdb
      POSTGRES_USER: weatheruser
      POSTGRES_PASSWORD: weatherpass

  # Redis for Celery
  redis:
    image: redis:alpine
    container_name: redis_broker
    restart: always

volumes:
  prodia:
  prodia_postgres_data: